# GENERAL SETTINGS ---------------------------------------
title: Emil Skydsgaard
author: Emil Skydsgaard
description: My Personal Website
email: emilskydsgaard@gmail.com
phone: +45 30 95 15 04
location: Copenhagen, Denmark


# ABOUT --------------------------------------------------
about: I am a software & computer engineer from Denmark with a background in electrical engineering and the creative media industry. 
  In my spare time I enjoy playing volleyball, doing fun projects with my friends and occasionally making videos for my YouTube channel or Instagram page.


# MENU ---------------------------------------------------
menu:
- {name: Projects, link: "/projects"}
- {name: Blog, link: "/blog"}
- {name: Contact, link: '#bottom'}


# HERO SECTION --------------------------------------------
hero:
  hero-bg: assets/images/backgrounds/abstract2.jpeg


# SOCIAL -------------------------------------------------
social:
- {icon: ti-github, link: "https://github.com/Emilostuff"}
- {icon: ti-linkedin, link: "https://www.linkedin.com/in/emilskydsgaard/"}
- {icon: ti-instagram, link: "https://www.instagram.com/emilostuff/"}
- {icon: ti-youtube, link: "https://www.youtube.com/emilostuff"}


# PROJECTS ------------------------------------------------
featured-projects:
  - algoaid
  - gearbox
  - ordle
  - ravi
  - plant-keeper
  - photo-booth

# Labels
portfolio-label:
- {title: SOFTWARE, type: software}
- {title: ELECTRONICS, type: electronics}
- {title: VIDEOS, type: videos}
- {title: MISC, type: misc}

# All Projects
portfolio-items:
  # 2022
  - image: "assets/images/projects/ordle_game.png"
    feature-gif: "https://i.imgur.com/3cpl4DZ.gif"
    url: ordle
    name: Ordle – Wordle in Danish
    year: 2022
    portfolio-type:
     - type: software

  - image: "assets/images/projects/pnp_machine.jpg"
    url: pnp
    name: Pick-and-Place Machine Based on a 3D Printer
    year: 2022
    portfolio-type:
     - type: electronics
    
  - image: "assets/images/projects/algoaid.jpg"
    url: algoaid
    name: Algoaid – A Learning Tool for Students 
    year: 2022
    portfolio-type:
     - type: software

  # 2021

  # 2020
  - image: "assets/images/projects/plant_keeper.jpg"
    feature-video: "https://www.youtube.com/embed/9Fx9zQJe3H4"
    url: plant-keeper
    name: Automated Plant Watering System
    year: 2020
    portfolio-type:
     - type: electronics
     - type: videos

  - image: "assets/images/projects/rotating-platform.jpg"
    feature-video: "https://www.youtube.com/embed/6-5eNO-go0M"
    url: photo-booth
    name: Photo Booth With a Rotating Platform
    year: 2020
    portfolio-type:
     - type: electronics
     - type: videos

  - image: "assets/images/projects/gearbox.jpg"
    feature-video: "https://www.youtube.com/embed/e12YoNOyO6M"
    url: gearbox
    name: 3D Printed Precision Gearbox 
    year: 2020
    portfolio-type:
     - type: electronics
     - type: videos

  - image: "assets/images/projects/tx.jpg"
    feature-video: "https://www.youtube.com/embed/I6TKGMbHcfo"
    url: arduino-tx
    name: Arduino Based Transmitter/Reciever
    year: 2020
    portfolio-type:
     - type: electronics
     - type: videos

  - image: "assets/images/projects/medst.jpg"
    url: medst
    name: The Public Management Evaluation
    year: 2020
    portfolio-type:
     - type: videos

# 2019
  - image: "assets/images/projects/ravi.jpg"
    feature-video: "https://www.youtube.com/embed/d_nGzPI5vDo"
    url: ravi
    name: We Are Ravi Kuma – Documentary Film
    year: 2019
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/lindpro.jpg"
    url: lindpro
    name: Lindpro – Promotional Films
    year: 2019
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/kims.jpg"
    url: kims
    name: Jørgens Hede Hule – Commercials
    year: 2019
    portfolio-type:
     - type: videos


# 2018
  - image: "assets/images/projects/cognitio.jpg"
    url: cognitio
    name: Cognitio – Short Film 
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/voksende.jpg"
    url: voksende-mennesker
    name: Voksende Mennesker – Short Film
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/kvalifik.jpg"
    feature-video: "https://www.youtube.com/embed/JcAev9UVA6s"
    url: kvalifik
    name: Vi er Kvalifik – Promotional Film
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/nupo.jpg"
    feature-video: "https://www.youtube.com/embed/FQtp2dJQR64"
    url: nupo
    name: Nupo – Commercial
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/videnskab.jpg"
    url: videnskab
    name: Videnskab er Lidenskab – Exhibition Films
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/fa09.jpg"
    feature-video: "https://www.youtube.com/embed/eV0Wumy8vIU"
    url: fa09
    name: FA09 – Promotional Film
    year: 2018
    portfolio-type:
     - type: videos

  - image: "assets/images/projects/weswapp.jpg"
    feature-video: "https://www.youtube.com/embed/GDWekDf25X0"
    url: weswapp
    name: WeSwapp – Commercial
    year: 2018
    portfolio-type:
     - type: videos

# 2017
  - image: "assets/images/projects/hugo-awards.jpg"
    url: hugo-awards
    name: Hugo Awards – Film Festival
    year: 2017
    portfolio-type:
     - type: videos

# 2016
  - image: "assets/images/projects/hansens.jpg"
    feature-video: "https://www.youtube.com/embed/AosLNZZoOgY"
    url: hansens-is
    name: Hansens Cykelløb – Promotional Film
    year: 2016
    portfolio-type:
     - type: videos
  
  - image: "assets/images/projects/nat.jpg"
    url: overnight-albums
    name: Overnight Albums
    year: 2016–2019
    portfolio-type:
     - type: misc


# 2014
  - image: "assets/images/projects/vektio.jpg"
    url: vektio
    name: Vektio - Smart Alarm Clock App
    year: 2014
    portfolio-type:
     - type: software

