# GENERAL SETTINGS ---------------------------------------
title: Emil Skydsgaard
author: Emil Skydsgaard
description: My Personal Website
email: emilskydsgaard@gmail.com
phone: +45 30 95 15 04
location: Copenhagen, Denmark


# ABOUT --------------------------------------------------
about: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.


# MENU ---------------------------------------------------
menu:
- {name: Projects, link: /projects}
- {name: Blog, link: /blog}
- {name: Contact, link: '#bottom'}


# HERO SECTION --------------------------------------------
hero:
  hero-bg: assets/images/backgrounds/abstract2.jpeg


# SOCIAL -------------------------------------------------
social:
- {icon: ti-github, link: https://github.com/Emilostuff}
- {icon: ti-linkedin, link: https://www.linkedin.com/in/emilskydsgaard/}
- {icon: ti-instagram, link: https://www.instagram.com/emilostuff/}
- {icon: ti-youtube, link: https://www.youtube.com/emilostuff}


# PROJECTS ------------------------------------------------
featured-projects:
  - pnp
  - ordle
  - plant-keeper

# Labels
portfolio-label:
- {title: SOFTWARE, type: software}
- {title: ELECTRONICS, type: electronics}
- {title: VIDEOS, type: videos}
- {title: MISC, type: misc}

# All Projects
portfolio-items:
  # 2022
  - image: assets/images/projects/ordle_game.png
    feature-gif: https://i.imgur.com/3cpl4DZ.gif
    url: /ordle
    id: ordle
    name: Ordle – Wordle in Danish
    year: 2022
    portfolio-type:
     - type: software

  - image: assets/images/projects/pnp_machine.jpg
    url: /pnp
    id: pnp
    name: Pick-and-Place Machine Based on a 3D Printer
    year: 2022
    portfolio-type:
     - type: electronics

  # 2021
  - image: https://img.youtube.com/vi/9Fx9zQJe3H4/maxresdefault.jpg
    feature-video: https://www.youtube.com/embed/9Fx9zQJe3H4
    url: /plant-keeper
    id: plant-keeper
    name: Automated Plant Watering System
    year: 2021
    portfolio-type:
     - type: electronics
     - type: videos


